"""add_deleted_at_to_saved_articles

Revision ID: b14cfb63970a
Revises: 5b7249323eda
Create Date: 2026-03-16 21:15:43.231254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b14cfb63970a'
down_revision: Union[str, None] = '5b7249323eda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_articles', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_articles', 'deleted_at')
    # ### end Alembic commands ###

